name: Node CI

on:
  push:
    branches:
      - github-actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies
        run: |
          cd src
          npm install
      - name: Run linter
        run: |
          cd src
          npm run lint
      - name: Run tests
        run: |
          cd src
          npm test
      - name: Prepare packaging
        run: |
          cd src
          npm prune --production
          rm -rf tests
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws --version
          aws s3 ls
